org: gabtim
console: true
service: gabtim-node-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  createBook:
    handler: src/controllers/bookController.createBook
    events:
      - httpApi:
          path: /book/create
          method: post
  getBooks:
    handler: src/controllers/bookController.getBooks
    events:
      - httpApi:
          path: /book
          method: get
  listCars:
    handler: src/services/swipeCar.listCars
    events:
      - httpApi:
          path: /cars
          method: get
  getCar:
    handler: src/services/swipeCar.getCar
    events:
      - httpApi:
          path: /cars/{id}
          method: get

resources:
  Resources:
    booksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: booksTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1